version: '3.4'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=file-processor'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=fileprocessor'
    ports:
      - '3307:3306'
    networks:
      - medidoc
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - medidoc
  mqtt:
    image: "eclipse-mosquitto:latest"
    ports:
      - "1885:1883"
    volumes:
      - ./config:/mosquitto/config:rw
    networks:
      - medidoc
  file-processor:
    image: "ghcr.io/iubh-seminars-assignments/file-processor:main"
    restart: on-failure
    environment:
      - spring_profiles_active=docker
    networks:
      - medidoc
    depends_on:
      - mqtt
      - mysql
  file-uploader:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mqtt
      - redis
    networks:
      - medidoc
networks:
  medidoc:
